#cloud-config
packages:
  - python3
  - git
  - haproxy

runcmd:
  - set -e
  - echo "Task Initiated" > /tmp/init.log
  - cd /home/ec2-user || exit 1

  # Update system packages
  - sudo yum update -y >> /tmp/init.log 2>&1
  - sudo yum install -y gcc python3-devel >> /tmp/init.log 2>&1

  # Install Python dependencies
  - sudo pip3 install boto3 >> /tmp/init.log 2>&1

  # Clone Caldera repository
  - sudo -u ec2-user git clone https://github.com/mitre/caldera.git --recursive --branch 4.1.0 >> /tmp/init.log 2>&1
  - cd caldera

  # Install required Python packages
  - sudo -u ec2-user pip3 install -r requirements.txt >> /tmp/init.log 2>&1
  - sudo -u ec2-user pip3 install marshmallow-enum==1.5.1 ldap3==2.7 aioftp==0.21.4 >> /tmp/init.log 2>&1

  # Modify configuration file
  - sudo chmod 777 conf/local.yml
  - sudo sed -i '/^\s*red:\s/s/:.*/:\ PassAccess0/' conf/local.yml
  - sudo sed -i '/^\s*blue:\s/s/:.*/:\ PassAccess0/' conf/local.yml

  # Create and configure a systemd service
  - echo "[Unit]" > /etc/systemd/system/caldera.service
  - echo "Description=Caldera C2 Service" >> /etc/systemd/system/caldera.service
  - echo "[Service]" >> /etc/systemd/system/caldera.service
  - echo "User=ec2-user" >> /etc/systemd/system/caldera.service
  - echo "WorkingDirectory=/home/ec2-user/caldera" >> /etc/systemd/system/caldera.service
  - echo "ExecStart=/usr/bin/python3 /home/ec2-user/caldera/server.py" >> /etc/systemd/system/caldera.service
  - echo "[Install]" >> /etc/systemd/system/caldera.service
  - echo "WantedBy=multi-user.target" >> /etc/systemd/system/caldera.service

  # Enable and start Caldera service
  - systemctl daemon-reload >> /tmp/init.log 2>&1
  - systemctl enable caldera >> /tmp/init.log 2>&1
  - systemctl start caldera >> /tmp/init.log 2>&1

  # Extract the password and save it
  - cat conf/local.yml | grep -oP '^\s+red:\s(?<Password>[\w\d_\-]+)' > /tmp/password
  - echo "Deployment Complete" >> /tmp/init.log
